In [8]:
import audata
import h5py as h5
from os import listdir
import pandas as pd
import time
from datetime import datetime

In [2]:
files = listdir('/zfsauton/data/public/gwelter/AUView/projects/conditionc/originals')

In [69]:
pd.set_option('display.float_format', lambda x: '%.6f' % x)

In [70]:
df = pd.DataFrame(columns = ['filename', 'oldval', 'newval', 'oldtime', 'newtime', 'diff', 'addtoann'])
for i in range(len(files)):
    f = files[i]
    try:
        oldf = h5.File('/zfsauton/data/public/gwelter/AUView/projects/old/ConditionC/originals/'+f, 'r')
        newf = audata.File.open('/zfsauton/data/public/gwelter/AUView/projects/conditionc/originals/'+f)
    except:
        continue
    if 'numerics' in oldf.keys():
        
        oldentry = oldf['numerics/HR.HR/data'][0]
        newentry = newf['data/numerics/HR.HR'][0]
        
        oldts = oldentry[0] + oldf['meta'].attrs['baseTime']
        newts = newentry['time'][0].timestamp()
        diff = (newts-oldts)/60/60
        
        addtoann = oldf['meta'].attrs['baseTime'] + (newts-oldts)
        
        df.loc[i] = [f, oldentry[1], newentry['value'][0], datetime.fromtimestamp(oldts), newentry['time'][0], diff, addtoann]

df

/home/gwelter/miniconda3/envs/medview/lib/python3.6/site-packages/dateutil/parser/_parser.py:1218: UnknownTimezoneWarning: tzname LMT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)

,filename,oldval,newval,oldtime,newtime,diff,addtoann
0,20190805_1871139_1633671.h5,87.000000,87.000000,2017-12-10 19:29:00.000,2017-12-10 19:29:00-05:00,0.000000,1512422760.000000
1,20190805_1746688_1212931.h5,91.000000,91.000000,2017-07-06 09:08:15.401,2017-07-06 08:08:15.401000-04:00,-1.000000,1499094862.985000
2,20190610_1962121_1549083_missingdata.h5,65.000000,65.000000,2016-09-20 10:52:22.356,2016-09-20 10:52:22.356000-04:00,0.000000,1473893400.000000
3,20190805_1344311_1441357.h5,116.000000,116.000000,2018-02-22 06:52:24.431,2018-02-22 06:52:24.431000-05:00,0.000000,1519171246.091000
4,20190805_1157669_1498169.h5,62.000000,62.000000,2018-10-15 06:53:56.666,2018-10-15 05:53:56.666000-04:00,-1.000000,1539541200.000000
6,20191112_1510496_1269489.h5,80.000000,80.000000,2017-06-11 14:52:14.890,2017-06-11 14:52:14.890000-04:00,0.000000,1496085133.120000
7,20190523_1369679_1282358_missingdata.h5,0.000000,0.000000,2016-08-06 20:46:52.803,2016-08-06 20:46:52.803000-04:00,0.000000,1470504060.000000
9,20190523_1133215_1572634.h5,128.000000,128.000000,2018-07-03 21:44:00.884,2018-07-03 20:44:00.884000,-5.000000,1530344872.180000
10,20191112_1850472_1561810.h5,104.000000,104.000000,2018-07-16 23:56:00.000,2018-07-16 23:56:00-04:00,0.000000,1530762120.000000
11,20190523_1828366_1967550.h5,70.000000,70.000000,2017-05-07 12:50:00.000,2017-05-07 11:50:00-04:00,-1.000000,1493594160.000000
12,20190523_1702934_1530565.h5,80.000000,80.000000,2017-12-06 09:05:36.703,2017-12-06 10:05:36.703000-05:00,1.000000,1512138494.445000
13,20190523_1397747_1900167.h5,104.000000,104.000000,2017-11-04 01:12:02.914,2017-11-04 01:12:02.914000-04:00,0.000000,1508627220.000000
14,20190523_1628452_1284339_missingdata.h5,63.000000,63.000000,2018-04-20 16:35:40.602,2018-04-20 16:35:40.602000-04:00,0.000000,1522575180.000000
16,20190523_1769089_1083631_missingdata.h5,80.000000,80.000000,2017-11-06 17:13:30.335,2017-11-06 18:13:30.335000-05:00,1.000000,1509895200.000000
17,20191112_1802215_1882581_missingdata.h5,63.000000,63.000000,2018-07-10 21:15:18.364,2018-07-10 21:15:18.364000-04:00,0.000000,1531244820.000000
19,20190805_1066221_1145914.h5,90.000000,90.000000,2018-02-04 01:25:06.371,2018-02-04 01:25:06.371000,-5.000000,1517235611.843000
20,20190523_1954542_1779418.h5,102.000000,102.000000,2017-05-04 16:27:02.994,2017-05-04 16:27:02.994000-04:00,0.000000,1493471404.246000
21,20190523_1369811_1829132.h5,98.000000,98.000000,2017-11-04 14:38:31.949,2017-11-04 14:38:31.949000-04:00,0.000000,1509242734.000000
22,20190805_1412855_1807867_missingdata.h5,115.000000,115.000000,2018-07-13 21:09:42.502,2018-07-13 21:09:42.502000-04:00,0.000000,1531504380.000000
23,20190523_1053954_1173378.h5,66.000000,66.000000,2018-01-10 01:22:06.866,2018-01-10 01:22:06.866000-05:00,0.000000,1515418233.874000
24,20190523_1987885_1136640.h5,99.000000,99.000000,2017-05-04 17:26:37.693,2017-05-04 17:26:37.693000-04:00,0.000000,1493898060.000000
25,20190523_1932256_1329004_missingdata.h5,82.000000,82.000000,2018-01-08 06:17:54.165,2018-01-08 07:17:54.165000-05:00,1.000000,1515340800.000000
26,20191112_1130145_1266994.h5,103.000000,103.000000,2018-02-21 21:44:53.527,2018-02-21 22:44:53.527000-05:00,1.000000,1518688620.000000
27,20190523_1524202_1653307.h5,56.000000,56.000000,2017-05-04 09:25:49.434,2017-05-04 09:25:49.434000-04:00,0.000000,1492526100.000000
28,20190523_1070382_1193704_missingdata.h5,92.000000,92.000000,2017-07-30 21:41:23.875,2017-07-30 21:41:23.875000-04:00,0.000000,1501353824.291000
29,20191112_1732978_1590540.h5,78.000000,78.000000,2017-08-27 20:38:58.109,2017-08-27 20:38:58.109000-04:00,0.000000,1503592828.189000
31,20190523_1627175_1430807.h5,110.000000,110.000000,2017-05-09 19:34:45.386,2017-05-09 19:34:45.386000-04:00,0.000000,1494091320.000000
32,20190523_1884037_1174266.h5,104.000000,104.000000,2017-07-10 18:43:05.552,2017-07-10 18:43:05.552000-04:00,0.000000,1499132666.114000
33,20191112_1177815_1697161.h5,133.000000,133.000000,2018-04-13 16:47:05.258,2018-04-13 16:47:05.258000-04:00,0.000000,1523591280.000000
34,20190523_1881766_1081324.h5,66.000000,66.000000,2016-11-22 02:21:57.249,2016-11-22 03:21:57.249000-05:00,1.000000,1479586471.553000
35,20190529_1012254_1312397.h5,120.000000,120.000000,2017-08-04 22:06:10.561,2017-08-04 22:06:10.561000-04:00,0.000000,1498001400.000000
36,20190523_1378692_1804652.h5,72.000000,72.000000,2018-02-26 20:40:44.536,2018-02-26 21:40:44.536000-05:00,1.000000,1519491242.946000
39,20191112_1903642_1927237.h5,99.000000,99.000000,2018-06-23 23:53:00.000,2018-06-23 23:53:00-04:00,0.000000,1527269940.000000
40,20190523_1879307_1277066.h5,96.000000,96.000000,2018-07-01 05:50:33.324,2018-07-01 05:50:33.324000-04:00,0.000000,1530044977.772000
41,20190523_1143071_1740434_missingdata.h5,97.000000,97.000000,2017-07-15 23:10:11.225,2017-07-15 23:10:11.225000-04:00,0.000000,1500125880.000000
42,20190523_1628905_1778103_missingdata.h5,96.000000,96.000000,2018-05-29 02:20:44.040,2018-05-29 02:20:44.040000-04:00,0.000000,1525957713.816000
43,20191112_1697994_1017281.h5,82.000000,82.000000,2017-12-11 20:02:14.002,2017-12-11 21:02:14.002000-05:00,1.000000,1511990052.506000
45,20190805_1008278_1978248.h5,108.000000,108.000000,2018-03-13 10:59:27.969,2018-03-13 09:59:27.969000-04:00,-1.000000,1520898082.240000
46,20190805_1875614_1829043.h5,87.000000,87.000000,2017-06-22 21:40:58.250,2017-06-22 20:40:58.250000-04:00,-1.000000,1498095458.121000
47,20190523_1287994_1046181.h5,87.000000,87.000000,2016-05-22 19:30:54.263,2016-05-22 19:30:54.263000-04:00,0.000000,1463931480.000000
48,20190523_1707728_1792754.h5,69.000000,69.000000,2017-03-01 07:35:57.818,2017-03-01 08:35:57.818000-05:00,1.000000,1488216108.409000

In [ ]:
df = pd.DataFrame(columns = ['filename', 'oldts', 'newts', 'diff'])
for i in range(len(files)):
    f = files[i]
    try:
        oldf = h5.File('/zfsauton/data/public/gwelter/AUView/projects/old/ConditionC/originals/'+f, 'r')
        newf = audata.File.open('/zfsauton/data/public/gwelter/AUView/projects/conditionc/originals/'+f)
    except:
        continue
    oldts = oldf['meta'].attrs['baseTime']
    newts = newf.time_reference.timestamp()
    df.loc[i] = [f, datetime.fromtimestamp(oldts), newf.time_reference, round((newts-oldts)/60/60, 2)]
df.sort_values(by=['diff'])

In [77]:
newf = audata.File.open('/zfsauton/data/public/gwelter/AUView/projects/conditionc/originals/20190523_1133215_1572634.h5')
ds = newf['/ehr/diagnostic_codes']
print(ds.columns)
ds = ds.get()
ds['time']

{'time': {'type': 'time'}, 'dxInd': {'type': 'factor', 'levels': ['Y'], 'ordered': False}, 'type': {'type': 'factor', 'levels': ['Final', 'Registration', 'Working'], 'ordered': False}, 'codeType': {'type': 'factor', 'levels': ['ICD-10-CM'], 'ordered': False}, 'seq': {'type': 'real'}, 'confirmStat': {'type': 'factor', 'levels': ['Confirmed'], 'ordered': False}, 'disp': {'type': 'factor', 'levels': ['Activity, other involving climbing, rappelling and jumping off', 'Adjustment disorder with mixed disturbance of emotions and conduct', 'Anxiety disorder, unspecified', 'Displaced intraarticular fracture of left calcaneus, initial encounter for closed fracture', 'Displaced intraarticular fracture of right calcaneus, initial encounter for closed fracture', 'Fall from, out of or through balcony, initial encounter', 'Hypokalemia', 'Injury, unspecified, initial encounter', 'Major depressive disorder, single episode, unspecified', 'Nicotine dependence, chewing tobacco, uncomplicated', 'Nicotine dependence, cigarettes, uncomplicated', 'Opioid abuse, uncomplicated', 'Other specified diseases of appendix', 'Patient room in hospital as the place of occurrence of the external cause', 'Poisoning by heroin, accidental (unintentional), initial encounter', 'Unspecified fracture of right calcaneus, initial encounter for closed fracture', 'Unspecified injury of left foot, initial encounter', 'Unspecified place in prison as the place of occurrence of the external cause', 'Unspecified viral hepatitis C without hepatic coma'], 'ordered': False}, 'lifeCycle': {'type': 'factor', 'levels': [], 'ordered': False}, 'source': {'type': 'factor', 'levels': ['MPACICD10', 'PowerChart/ProVide'], 'ordered': False}, 'code': {'type': 'factor', 'levels': ['B19.20', 'E87.6', 'F11.10', 'F17.210', 'F17.220', 'F32.9', 'F41.9', 'F43.25', 'K38.8', 'S92.001A', 'S92.061A', 'S92.062A', 'S99.922A', 'T14.90XA', 'T40.1X1A', 'W13.0XXA', 'Y92.149', 'Y92.230', 'Y93.39'], 'ordered': False}}

0    1800-03-14 12:00:00
1    1800-03-14 12:00:00
2    1800-03-14 12:00:00
3    1800-03-14 12:00:00
4    1800-03-14 12:00:00
5    1800-03-14 12:00:00
6    1800-03-14 12:00:00
7    1800-03-14 12:00:00
8    1800-03-14 12:00:00
9    1800-03-14 12:00:00
10   1800-03-14 12:00:00
11   1800-03-14 12:00:00
12   1800-03-14 12:00:00
13   1800-03-14 12:00:00
14   1800-03-14 12:00:00
15   1800-03-14 12:00:00
16   1800-03-14 12:00:00
17   2018-07-02 23:04:00
18   2018-07-03 23:04:00
19   2018-07-03 23:04:00
Name: time, dtype: datetime64[ns]